/**
 * Huculský šampionať API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Comment } from './comment';
import { Image } from './image';


export interface Article { 
    id?: number;
    date?: string;
    name?: string | null;
    content?: string | null;
    createdBy?: string | null;
    isApproved?: boolean;
    comments?: Array<Comment> | null;
    images?: Array<Image> | null;
}

