/**
 * Huculský šampionať API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Competition } from './competition';
import { Image } from './image';
import { Rider } from './rider';
import { Result } from './result';


export interface Horse { 
    id?: number;
    name?: string | null;
    number?: string | null;
    dateOfBirth?: string | null;
    male?: boolean;
    motherId?: number;
    fatherId?: number;
    riders?: Array<Rider> | null;
    results?: Array<Result> | null;
    competitions?: Array<Competition> | null;
    images?: Array<Image> | null;
}

