/**
 * Huculský šampionať API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Competition } from './competition';
import { Horse } from './horse';
import { Image } from './image';


export interface Rider { 
    id?: number;
    firstName?: string | null;
    lastName?: string | null;
    riderNumber?: string | null;
    category?: string | null;
    dateOfBirth?: string | null;
    horses?: Array<Horse> | null;
    competitions?: Array<Competition> | null;
    images?: Array<Image> | null;
}

